name: app_puskesmas_tugas_ri
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  
  # Firebase
  firebase_core: ^2.12.0
  cloud_firestore: ^4.9.0
  firebase_auth: ^4.6.0
  flutter_dotenv: ^5.1.0

  # Animation
  animate_do: ^3.3.4
  lottie: ^3.1.2

  # Icons
  flutter_svg: ^2.0.10+1

  # Storage
  shared_preferences: ^2.2.3

  # UI
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/data/
    - assets/fonts/
